### ISSUE TITLE
Default partition column name conflicts with reserved MySQL 'partition' keyword

### ISSUE THREAD

**Issue by puuj** [linqs/psl#11]
`partition` has become a reserved word since MySQL 5.6.2, thus leading to an exception when PSL tries to create its tables. PSL should use a name other than partition for that column.

Thanks @joe776 for reporting

**Comment by eriq-augustine** [comment]
MySQL support has been removed in favor of Postgres.
MySQL connectors have some issues that make them not compatible with the same functionality from H2 and Postgres without significant, hacky work.
