### ISSUE TITLE
Opened BufferedReader are not being closed

### ISSUE THREAD

**Issue by LingjiaDeng** [linqs/psl#12]
In [edu.umd.cs.psl.ui.data.file.util.LoadDelimitedData.java](https://github.com/linqs/psl/blob/7b247228157121b4ee5948f1202d62b77de5d29b/psl-core/src/main/java/edu/umd/cs/psl/ui/data/file/util/LoadDelimitedData.java), in the loadTabData function, on Line 38, a new BufferedReader is created for new data file. However, the ``in'' BufferedReader is not closed after the whole loop. If opening too many files, a PSL will report Java error Too many open files. (This may be the reason for this error)

Could someone add the in.close() to close the BufferedReader?

**Comment by matthewjhoward** [comment]
This has been fixed in the upcoming version 2.0; however, I added the fix to the master. Thanks!

**Comment by stephenbach** [comment]
Thanks Matt!

Lingjia, we'll be releasing a version 1.2.2 soon with the fix included.
