### ISSUE TITLE
Instantiating factories from config file fails when executing from Maven

### ISSUE THREAD

**Issue by stephenbach** [linqs/psl#2]
In PSL version 1.0.1:

If a factory is specified in `psl.properties`, e.g., 

``` properties
example.conicreasoner.conicprogramsolver = edu.umd.cs.psl.optimizer.conic.ipm.HomogeneousIPMFactory
```

and a program is executed from Maven with the command

``` shell
>> mvn exec:java -Dexec.mainClass=<fully qualified class name>
```

then the class loader cannot find the specified class, even if it is on the classpath.

Suspect that Maven uses its own class loader, so the jars containing the factories are not on the classpath of the class loader used by the ConfigManager.

**Comment by eriq-augustine** [comment]
This has probably been fixed long ago.
I ran the easy-lp example like this, and it ran fine.
