### ISSUE TITLE
Documentation of external functions

### ISSUE THREAD

**Issue by duhai-alshukaili** [linqs/psl#27]
This is a issue with current documentation of using external function.

The documentation says to use the following to define an external function in PSL.

model.add function: MyStringSimilarity, implementation: new MyStringSimilarity();

However, the above is likely to throw a cast exception. This should be corrected with

model.add function: “MyStringSimilarity”, implementation: new MyStringSimilarity();

**Comment by eriq-augustine** [comment]
Fixed.

Good catch.
Our documentation around external functions needs some work in general.
