### ISSUE TITLE
Unary Relationship Prediction

### ISSUE THREAD

**Issue by NarendraPatwardhan** [linqs/psl#271]
I am predicting a unary relationship (attribute) based on following simple rule in .psl file:
isConnected(A,B) & Attribute(A) & (A !=B) -> Attribute(B) ^2

I have loaded data for a simplistic case as follows
in Attribute_obs.txt:
0   1.0
2   1.0

in isConnected_obs.txt
0   1   1.0
1   2   1.0

in Attribute_targets.txt
1

I am getting the following error:

0    [main] INFO  org.linqs.psl.cli.Launcher  - Running PSL CLI Version 2.2.1-a573763
133  [main] INFO  org.linqs.psl.cli.Launcher  - Loading data
Unexpected exception!
java.lang.IllegalArgumentException: Data on row 0 length does not match for observations: Expecting: 2, Got: 1

Is the target formatting different in the newer version of PSL? If I am predicting for a unary relationship, why does the observation demand 2 entries on a single line?

**Comment by eriq-augustine** [comment]
Hey Narendra,

In your `isConnected_obs.txt` file (and all files), are the value separated with tabs?

---
Side note: Consult errors like this to elaborate on in #230 .

**Comment by NarendraPatwardhan** [comment]
Hi Eriq,
Yes I have kept all the values tab separated. Will also put a comment on in #23

**Comment by eriq-augustine** [comment]
No need to comment in #230, that's what my side note was for.

Can you supply a copy of your PSL directory?
Just a zip of everything we need to run, so we can test on our side.

**Comment by NarendraPatwardhan** [comment]
[simple-attribute.zip](https://github.com/linqs/psl/files/4646658/simple-attribute.zip)
Here you go. Also I am thankful for such a quick reply!

**Comment by eriq-augustine** [comment]
Thanks, and no problem on the quick replies.

It looks like there are actually spaces instead of tabs separating the columns.
Maybe your text editor has on soft tabs (which it should, but is inconvenient in this one use case).

I attached a new version with tabs instead of spaces, and it ran all the way through for me.
[simple-attribute-eq.zip](https://github.com/linqs/psl/files/4646692/simple-attribute-eq.zip)

**Comment by NarendraPatwardhan** [comment]
Thanks a lot! Works perfectly!

**Comment by eriq-augustine** [comment]
No problem, good luck.
Also, an alternative place to post is the PSL User's group:
https://groups.google.com/forum/#!forum/psl-users

More people have visibility there, just in case I am away.
