### ISSUE TITLE
Can PSL Framework deal with Chinese?

### ISSUE THREAD

**Issue by xinan711456** [linqs/psl#30]
Firstly, I learn PSL in short time. 
If you have a demo for Chinese（汉字、中文） or a tutorial for layman ,please send to my email 309135619@qq.com and I thank you very much.

**Comment by eriq-augustine** [comment]
Unfortunatley, we don't have a specific demo/tutorial in Chinese, but we do have several resources to get started with:
 - Video tutorial: https://www.youtube.com/watch?list=PLvdms0QyJYgxYA2O6bBBa918PLZE9h8Ie&v=EIe-JBE8kRg
 - PSL Journal Article: https://arxiv.org/abs/1505.04406
 - PSL Wiki: https://github.com/linqs/psl/wiki
 - PSL Examples: https://github.com/linqs/psl-examples

As you have already discovered, the PSL Users group is also great resource for asking questions.
We typically reserve issues for bugs and feature requests.
