### ISSUE TITLE
org.h2.jdbcSQLException: General error: "java.lang.NullPointerException"

### ISSUE THREAD

**Issue by Modestas96** [linqs/psl#317]
Hey, I'm trying to run PSL learning, and I get the following error, I tried installing and uninstalling the PSL software, and nothing seems to work, the error is thrown for all the examples in /linqs/psl-examples as well. So I think this is a general error. I do not know what caused this error to occur, it might have been an improper shutdown of the PSL cli or something else.

The error trace is bellow:

INFO:pslpython.model:0    [main] INFO  org.linqs.psl.cli.Launcher  - Running PSL CLI Version 2.2.2-5f9a472
ERROR:pslpython.model:1362 [main] ERROR com.zaxxer.hikari.pool.HikariPool  - HikariPool-1 - Exception during pool initialization.
ERROR:pslpython.model:(Unknown PSL logging level) -- org.h2.jdbc.JdbcSQLException: General error: "java.lang.NullPointerException" [50000-192]
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.message.DbException.get(DbException.java:168)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.message.DbException.convert(DbException.java:295)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.engine.Database.openDatabase(Database.java:301)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.engine.Database.<init>(Database.java:264)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.engine.Engine.openSession(Engine.java:64)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.engine.Engine.openSession(Engine.java:176)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.engine.Engine.createSession(Engine.java:137)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.engine.Engine.createSession(Engine.java:27)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:118)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:102)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.Driver.connect(Driver.java:72)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:112)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:428)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:499)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:112)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:72)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.linqs.psl.database.rdbms.driver.H2DatabaseDriver.<init>(H2DatabaseDriver.java:85)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.linqs.psl.cli.Launcher.initDataStore(Launcher.java:106)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.linqs.psl.cli.Launcher.run(Launcher.java:389)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.linqs.psl.cli.Launcher.main(Launcher.java:466)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.linqs.psl.cli.Launcher.main(Launcher.java:454)
ERROR:pslpython.model:(Unknown PSL logging level) -- Caused by: java.lang.NullPointerException
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.mvstore.db.ValueDataType.compare(ValueDataType.java:103)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.mvstore.MVMap.compare(MVMap.java:708)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.mvstore.Page.binarySearch(Page.java:334)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.mvstore.MVMap.binarySearch(MVMap.java:461)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.mvstore.MVMap.get(MVMap.java:450)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.mvstore.MVMap.remove(MVMap.java:538)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.mvstore.db.TransactionStore.rollbackTo(TransactionStore.java:502)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.mvstore.db.TransactionStore$Transaction.rollback(TransactionStore.java:799)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.mvstore.db.MVTableEngine$Store.initTransactions(MVTableEngine.java:255)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.engine.Database.open(Database.java:762)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.engine.Database.openDatabase(Database.java:270)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	... 22 more
ERROR:pslpython.model:(Unknown PSL logging level) -- Unexpected exception!
ERROR:pslpython.model:(Unknown PSL logging level) -- com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: General error: "java.lang.NullPointerException" [50000-192]
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:528)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:520)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:112)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:72)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.linqs.psl.database.rdbms.driver.H2DatabaseDriver.<init>(H2DatabaseDriver.java:85)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.linqs.psl.cli.Launcher.initDataStore(Launcher.java:106)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.linqs.psl.cli.Launcher.run(Launcher.java:389)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.linqs.psl.cli.Launcher.main(Launcher.java:466)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.linqs.psl.cli.Launcher.main(Launcher.java:454)
ERROR:pslpython.model:(Unknown PSL logging level) -- Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.NullPointerException" [50000-192]
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.message.DbException.get(DbException.java:168)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.message.DbException.convert(DbException.java:295)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.engine.Database.openDatabase(Database.java:301)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.engine.Database.<init>(Database.java:264)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.engine.Engine.openSession(Engine.java:64)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.engine.Engine.openSession(Engine.java:176)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.engine.Engine.createSession(Engine.java:137)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.engine.Engine.createSession(Engine.java:27)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:118)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:102)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.Driver.connect(Driver.java:72)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:112)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:428)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:499)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	... 7 more
ERROR:pslpython.model:(Unknown PSL logging level) -- Caused by: java.lang.NullPointerException
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.mvstore.db.ValueDataType.compare(ValueDataType.java:103)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.mvstore.MVMap.compare(MVMap.java:708)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.mvstore.Page.binarySearch(Page.java:334)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.mvstore.MVMap.binarySearch(MVMap.java:461)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.mvstore.MVMap.get(MVMap.java:450)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.mvstore.MVMap.remove(MVMap.java:538)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.mvstore.db.TransactionStore.rollbackTo(TransactionStore.java:502)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.mvstore.db.TransactionStore$Transaction.rollback(TransactionStore.java:799)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.mvstore.db.MVTableEngine$Store.initTransactions(MVTableEngine.java:255)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.engine.Database.open(Database.java:762)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	at org.h2.engine.Database.openDatabase(Database.java:270)
ERROR:pslpython.model:(Unknown PSL logging level) -- 	... 22 more
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/mnt/c/Program Files/JetBrains/PyCharm 2021.1.3/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/mnt/c/Program Files/JetBrains/PyCharm 2021.1.3/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/mnt/c/Users/jurci/Desktop/Master Thesis/TeacherStudentNetworks/run_movielens.py", line 113, in <module>
    run(5)
  File "/mnt/c/Users/jurci/Desktop/Master Thesis/TeacherStudentNetworks/run_movielens.py", line 83, in run
    run_core_psl(fold=0, frac_data=data_fraction, output_path='core_psl_predictions/movielens',
  File "/mnt/c/Users/jurci/Desktop/Master Thesis/TeacherStudentNetworks/run_psl.py", line 36, in run
    learn_model(psl_model, rule_list, predicate_list, path_to_learn, output_path)
  File "/mnt/c/Users/jurci/Desktop/Master Thesis/TeacherStudentNetworks/run_psl.py", line 70, in learn_model
    psl_model.learn(jvm_options=['-Xms4096M', '-Xmx12000M'])
  File "/home/modestas/miniconda3/lib/python3.8/site-packages/pslpython/model.py", line 209, in learn
    self._run_psl(data_file_path, rules_file_path, cli_options, psl_config, jvm_options, logger)
  File "/home/modestas/miniconda3/lib/python3.8/site-packages/pslpython/model.py", line 485, in _run_psl
    raise ModelError("PSL returned a non-zero exit status: %d." % (exit_status))
pslpython.model.ModelError: PSL returned a non-zero exit status: 1.

**Comment by eriq-augustine** [comment]
I have not been able to reproduce this error on any psl-examples.

I would first try removing any existing H2 databases that are on disk (corrupted ones can sometimes cause errors).
To see the exact location, just run the cli with `--help`.
It defaults to the system's temp directory then 'cli_<user name>@<host name>'.

If that doesn't work, then can you post another stacktrace with an unmodified psl-example.

**Comment by Modestas96** [comment]
Yes, I can confirm that deleting the H2 database file in the temp directory solved this issue!
