### ISSUE TITLE
Unable to build from source

### ISSUE THREAD

**Issue by saraswat** [linqs/psl#33]
Running `mvn install` (3.5.2) gets:
```
 Failed to execute goal on project psl-core: Could not resolve dependencies for project edu.umd.cs:psl-core:jar:1.2.1: Failed to collect dependencies at edu.emory.mathcs:parallelcolt:jar:0.9.4: Failed to read artifact descriptor for edu.emory.mathcs:parallelcolt:jar:0.9.4: Could not transfer artifact edu.emory.mathcs:parallelcolt:pom:0.9.4 from/to psl-releases (https://scm.umiacs.umd.edu/maven/lccd/content/repositories/psl-releases/): Failed to transfer file: https://scm.umiacs.umd.edu/maven/lccd/content/repositories/psl-releases/edu/emory/mathcs/parallelcolt/0.9.4/parallelcolt-0.9.4.pom. Return code is: 503 , ReasonPhrase:Service Unavailable. -> [Help 1]
```

Problem with umd.edu server?

**Comment by eriq-augustine** [comment]
Our maven repository has moved as detailed in the wiki migration page for 2.0.0:
https://github.com/linqs/psl/wiki/Migrating-to-PSL-2#maven-repository-move

**Comment by eriq-augustine** [comment]
I recommend moving up to at least version 2.0.0 (the latest stable release).
The migration guide I linked before should help you with that.

You can also take a look at the PSL examples:
https://github.com/linqs/psl-examples
They are using our current development release, so they are a bit more forward than 2.0.0.

This is on the wiki, but you can also check out the api documentation (and wiki) for each release here:
https://linqs-data.soe.ucsc.edu/psl-docs/
