### ISSUE TITLE
support arbitrary constant (PSLParser)

### ISSUE THREAD

**Issue by binh-vu** [linqs/psl#34]
In ```PSL.g4```
```
constant
    :   SINGLE_QUOTE IDENTIFIER SINGLE_QUOTE
    |   DOUBLE_QUOTE IDENTIFIER DOUBLE_QUOTE
    ;
```

Since a constant is quoted within single double or double quote, it would be better if user can use any character instead of just letter and digit (e.g: using delimiter to make constant easier to read and debug)

In addition to this, may be lots of people will get confuse if they have this error: ```org.antlr.v4.runtime.NoViableAltException``` because of constant parsing.

**Comment by eriq-augustine** [comment]
I created an issue for this in our development fork:
https://github.com/eriq-augustine/psl/issues/159

(This is the correct place to report this issue. We typically use this canonical repo's issues listing for high-level issues and triage.)

**Comment by eriq-augustine** [comment]
This has been complete.
See https://github.com/eriq-augustine/psl/issues/159 for details.
