### ISSUE TITLE
Some questions about the data for weight learning.

### ISSUE THREAD

**Issue by liu-yang-maker** [linqs/psl#342]
Excuse me, I'm a little confused about the data for weight learning.

The process contains two parts: weight learning and inference. I wanna ask what is the use of the target/truth data in weight learning. I think we only need observation data for weight learning. And another question is that why the observation data in infer and learn of a closed predicate is different?

Thanks for you attention!

**Comment by dickensc** [comment]
Hello and thanks for the question.

 I will be using terminology from the [core PSL paper](https://linqs.org/assets/resources/bach-jmlr17.pdf) and the [PSL Glossary](https://psl.linqs.org/wiki/Glossary.html) to answer your questions.

You are correct in that commonly there are two data settings that are used in a PSL application and they are referred to as `learn` and `infer`. Examples of this can be seen in a [psl-example JSON configuration file](https://github.com/linqs/psl-examples/blob/main/cora/cli/cora.json).

The data for predicates in both the `learn` and `infer` settings is partitioned into `observations`, `targets`, and `truth`. The user specifies what data belongs to each partition by providing a path to data files for each predicate. Again I refer to the link above for an example of this. In both settings `observations` and `targets` are data that define the ground HL-MRF model. `observations` data defines observations, $\mathbf{x}$, and `targets` define targets, $\mathbf{y}$, in definition  3 (HL-MRFs) of the [core PSL paper](https://linqs.org/assets/resources/bach-jmlr17.pdf). In summary:

- `observations` is data that is observed, i.e., used to create ground atoms with an immutable value that is not inferred/predicted by PSL. 
- `targets` is data that is unobserved, i.e., used to create ground atoms with an "unknown" value. PSL runs inference to make predictions for this data.
- `truth` is data that is labeled. This data is used solely for evaluations of prediction performance or learning losses. Typically, this data is a subset the target data (though this is not a requirement).

In the `learn` setting the `truth` data is used to evaluate a learning loss. At a very high-level a weight learner will:

(1) ground, i.e., build an HL-MRF, using data in the `observations` and `targets` partitions of each predicate,
(2) perform inference to obtain values/predictions for the `target` variables, 
(3) evaluate a learning loss/objective using `truth` data and the current predictions, (ex. MSE of target values and truth values)
(4) update model weights
(5) if the evaluated objective satisfies stopping criterion stop, else goto (2)

In the `learn` setting the `truth` data is used to evaluate prediction performance after inference (ex. categorical accuracy of target values w.r.t. truth values).

You also mentioned open and closed predicates and asked why the observation data of a closed predicate may differ in the `learn` vs `infer` setting. Open predicates are predicates whose atoms can be observed or unobserved. Closed predicates are those with only observed atoms. Thus closed predicate observations may differ between `learn` and `infer` anytime you change or add observations between training and evaluation/application of the model. This happens often. For instance, links or citations between papers in a citation network may be modeled as closed predicates (as in the linked example above) and in `learn` we train our model using citations and papers observed up to some date and then in `infer` we evaluate using all observed citations and papers up to a later date.

**Comment by liu-yang-maker** [comment]
Appreciate for your great reply!
