### ISSUE TITLE
I run the groovy's run.sh in the win7 command line(using Cygwin)

### ISSUE THREAD

**Issue by th0o0** [linqs/psl#38]
Running PSL
Error: Could not find or load main class org.linqs.psl.examples.simpleacquaintances.Run
ERROR: Failed to run

**Comment by th0o0** [comment]
I find the [link,](https://groups.google.com/forum/#!topic/psl-users/F4jerZwO4Q8) but I don't konw how to fix the run.sh.
Thinks!

**Comment by eriq-augustine** [comment]
The invocation of Java in this script looks like:
```
java -cp ./target/classes:$(cat ${CLASSPATH_FILE}) ${TARGET_CLASS}
```

As Raul said in that link, `cat` is not available in Cygwin.
(I don't use Cygwin, but I think the easiest solution would just be to install `cat`.)

So to get it working without cat, you just need to replace `$(cat ${CLASSPATH_FILE})` with the entire contents of `CLASSPATH_FILE` (usually `classpath.out`).
Note that there is not newline in this file.

**Comment by th0o0** [comment]
I have installed `cat` in the Cygwin, but the I get the error again. When I run the code in Ubuntu, everything runs well.

**Comment by eriq-augustine** [comment]
Did you try replacing `$(cat ${CLASSPATH_FILE})` with the contents of `CLASSPATH_FILE`?

**Comment by th0o0** [comment]
I did, but get a lot of messy code(my OS language is Chinese) and  get the same error `Error: Could not find or load main class org.linqs.psl.examples.simpleacquaintances.Run`

**Comment by eriq-augustine** [comment]
I think I understand the issue now.
I don't think it was the same as Raul's.

Since it is complaining about a class in this project, I think that the first part of the classpath is the broken part.
Can you run `mvn compile` successfully?
Does the `./target/classes` directory exist?

What happens if you run:
```
java -cp ./target/classes:$(cat ${CLASSPATH_FILE}) ${TARGET_CLASS}
```
I expect that it will give an error (since we didn't include all the required dependencies), but hopefully it will not complain about `org.linqs.psl.examples.simpleacquaintances.Run`.

**Comment by th0o0** [comment]
1. `mvn compile` can run successfully
$ mvn compile
[INFO] Scanning for projects...
[INFO]
[INFO] ------------< org.linqs.psl.examples:simple-acquaintances >-------------
[INFO] Building simple-acquaintances 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ simple-acquaintances ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ simple-acquaintances ---
[INFO] Changes detected - recompiling the module!
[INFO] Using Groovy-Eclipse compiler to compile both Java and Groovy files
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.337 s
[INFO] Finished at: 2018-07-31T10:53:19+08:00
[INFO] ------------------------------------------------------------------------

2. the` ./target/classes` directory exist(the `Run.class` also exist)

3.when I run `java -cp ./target/classes org.linqs.psl.examples.simpleacquaintances.Run` under the groovy folder，I get the error 
`Error: Could not find or load main class org.linqs.psl.examples.simpleacquaintances.Run`

**Comment by eriq-augustine** [comment]
I think this may be the issue:
https://stackoverflow.com/questions/16140668/error-could-not-find-or-load-main-class-java-cygwin
https://stackoverflow.com/questions/9690756/how-to-run-java-from-cygwin

Looks like there are two issues here:
1. Windows uses `;` instead of `:` as a path separator.
2. All paths need to be windows-style.

I am not on a Windows machine to test, but replacing the java invocation with something like this may work:
```
java -cp ./target/classes;$(cat ${CLASSPATH_FILE} | sed 's/;/:/g' | xargs cygpath -pw) ${TARGET_CLASS}
```

**Comment by th0o0** [comment]
My `classpath.out`  as flollows, but I get the same error
(`Error: Could not find or load main class org.linqs.psl.examples.simpleacquaintances.Run`)


`classpath.out` is 
`D:/m2/maven_repository/org/linqs/psl-groovy/CANARY-2.1.6/psl-groovy-CANARY-2.1.6.jar;D:/m2/maven_repository/org/linqs/psl-core/CANARY-2.1.6/psl-core-CANARY-2.1.6.jar;D:/m2/maven_repository/edu/emory/mathcs/parallelcolt/0.9.4/parallelcolt-0.9.4.jar;D:/m2/maven_repository/edu/emory/mathcs/jplasma/1.2/jplasma-1.2.jar;D:/m2/maven_repository/log4j/log4j/1.2.17/log4j-1.2.17.jar;D:/m2/maven_repository/org/slf4j/slf4j-api/1.7.21/slf4j-api-1.7.21.jar;D:/m2/maven_repository/org/slf4j/slf4j-log4j12/1.7.21/slf4j-log4j12-1.7.21.jar;D:/m2/maven_repository/com/google/guava/guava/20.0/guava-20.0.jar;D:/m2/maven_repository/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar;D:/m2/maven_repository/org/apache/commons/commons-collections4/4.1/commons-collections4-4.1.jar;D:/m2/maven_repository/org/apache/commons/commons-configuration2/2.2/commons-configuration2-2.2.jar;D:/m2/maven_repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar;D:/m2/maven_repository/com/h2database/h2/1.4.192/h2-1.4.192.jar;D:/m2/maven_repository/org/postgresql/postgresql/42.1.3.jre7/postgresql-42.1.3.jre7.jar;D:/m2/maven_repository/com/healthmarketscience/sqlbuilder/sqlbuilder/2.1.7/sqlbuilder-2.1.7.jar;D:/m2/maven_repository/com/healthmarketscience/common/common-util/1.1.1/common-util-1.1.1.jar;D:/m2/maven_repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar;D:/m2/maven_repository/com/zaxxer/HikariCP-java7/2.4.13/HikariCP-java7-2.4.13.jar;D:/m2/maven_repository/joda-time/joda-time/2.9.4/joda-time-2.9.4.jar;D:/m2/maven_repository/org/linqs/psl-parser/CANARY-2.1.6/psl-parser-CANARY-2.1.6.jar;D:/m2/maven_repository/org/antlr/antlr4-runtime/4.5/antlr4-runtime-4.5.jar;D:/m2/maven_repository/org/abego/treelayout/org.abego.treelayout.core/1.0.1/org.abego.treelayout.core-1.0.1.jar;D:/m2/maven_repository/org/codehaus/groovy/groovy-eclipse-batch/2.4.3-01/groovy-eclipse-batch-2.4.3-01.jar;D:/m2/maven_repository/org/codehaus/groovy/groovy-all/2.4.7/groovy-all-2.4.7.jar`

**Comment by eriq-augustine** [comment]
Looks like it is still not picking up `./target/classes` in the classpath.
Try explicitly putting in the output of:
```
cygpath -wp ./target/classes
```

**Comment by th0o0** [comment]
I'm sorry, I am a new comer to the shell. Your means add the `cygpath -wp ./target/classes` to the `classpath.out` file? if yes, how to to.

 Thanks

**Comment by eriq-augustine** [comment]
What I mean is that we want to use the output of this command:
```
cygpath -wp ./target/classes
```
In place of `./target/classes`.

So you should try replacing:
```
java -cp ./target/classes:$(cat ${CLASSPATH_FILE}) ${TARGET_CLASS}
```

With:
```
java -cp $(cygpath -wp ./target/classes)\;$(cat ${CLASSPATH_FILE}) ${TARGET_CLASS}
```

**Comment by th0o0** [comment]
appreciate your help and patience, the problem solved.

**Comment by eriq-augustine** [comment]
Yay!
Good to hear.
