### ISSUE TITLE
ExternalFunction implementations use the wrong method on StringAttribute

### ISSUE THREAD

**Issue by JackSullivan** [linqs/psl#4]
Several of the ExternalFunction implementations (I noticed `LevenshteinSimilarity`, `SubStringSimilarity`, and `CosineSimilarity`) use `toString()` to convert `GroundTerm` instances to strings. Based on my reading of the code, this is incorrect, as this should concretely dispatch to `StringAttribute` whose `toString()` method returns a truncated string as follows:
```java
public String toString() {
		if (value.length() > 28)
			return "'" + value.substring(0, Math.min(value.length(), 25)) + "...'";
		else
			return "'" + value + "'";
	}
```

Rather, these calls should be to the `getValue()` method, which simply returns the value. If my interpretation of the dispatch here is correct please let me know and I'll go through and submit a pull request with fixes throughout `ExternalFunction` implementers.

**Comment by WhiteAu** [comment]
Why is there a gap between the conditional check 28) and the min value 25)?

**Comment by WhiteAu** [comment]
Didn't read eclipses, nvm.

**Comment by stephenbach** [comment]
This is indeed a bug! We're preparing a 1.2 release that should be backwards compatible with 1.1.1, so if you want to fork off of the develop branch, that should be most convenient. Thanks!

**Comment by stephenbach** [comment]
Fixed by https://github.com/linqs/psl/commit/7e0da7360ee840a2000f14ca35322a556e2efd2c
