### ISSUE TITLE
groovy project ./run.sh get an error

### ISSUE THREAD

**Issue by th0o0** [linqs/psl#41]
I rewrite the groovy project for my own, but when I run the `run.sh` I get an error:
$ mvn clean
[INFO] Scanning for projects...
[INFO]
[INFO] -------------< org.linqs.psl.examples:simpleacquaintances >-------------
[INFO] Building simpleacquaintances 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ simpleacquaintances ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.197 s
[INFO] Finished at: 2018-08-01T20:08:59+08:00
[INFO] ------------------------------------------------------------------------

 /cygdrive/d/kgi/groovy
$ ./run.sh
[INFO] Scanning for projects...
[INFO]
[INFO] -------------< org.linqs.psl.examples:simpleacquaintances >-------------
[INFO] Building simpleacquaintances 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for org.linqs:psl-groovy:jar:CANARY-2.1.6 is missing, no dependency information available
[WARNING] The POM for org.linqs:psl-cli:jar:CANARY is missing, no dependency information available
[WARNING] The POM for org.linqs:psl-dataloading:jar:CANARY is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.167 s
[INFO] Finished at: 2018-08-01T20:26:13+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project simpleacquaintances: Could not resolve dependencies for project org.linqs.psl.examples:simpleacquaintances:jar:1.0.0-SNAPSHOT: Failure to find org.linqs:psl-groovy:jar:CANARY-2.1.6 in http://maven.aliyun.com/nexus/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of nexus-aliyun has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
ERROR: Failed to compile

- I guess I can't download the psl relative jar in the mirror,  but in my local repository I have downloaded the three jars.

**Comment by eriq-augustine** [comment]
I am not sure what your issue is.
Is there a reason you cannot use our maven repository?
http://maven.linqs.org/maven/repositories/psl-releases/

If for some reason you can't, then I suggest building from source instead of trying to manually download the resources.

By the way, for non-issues like this it would be better to post them to the users' group:
https://groups.google.com/forum/#!forum/psl-users

**Comment by th0o0** [comment]
ok,  thanks for your reply.
