### ISSUE TITLE
Seems that the value of primalRes and epsilonPrimal goes wrong in this version of code...

### ISSUE THREAD

**Issue by thiswill** [linqs/psl#43]
I've been running **social-network-analysis** in PSL-example using this version of source code. Previously, it normally ends in 40secs. However, this time the PSL program stuck in optimization phase until 25000 iterations.

I printed stopping criteria and saw that **primalRes > epsilonPrimal** always holds. So I tried to let **epsilonPrimal = 2 * epsilonPrimal** and the program ended with 479 iterations.

**Comment by eriq-augustine** [comment]
What version are you using?
I just ran it with the latest release and didn't have any issues:
```
eriq@box:~/code/psl-examples/social-network-analysis/cli$ ./run.sh 
Downloading data file with command: 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1628k  100 1628k    0     0  4353k      0 --:--:-- --:--:-- --:--:-- 4353k
Extracting the data tar
Downloading psl-jar file located at: 'https://linqs-data.soe.ucsc.edu/maven/repositories/psl-releases/org/linqs/psl-cli/2.1.0/psl-cli-2.1.0.jar'.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13.9M  100 13.9M    0     0  8054k      0  0:00:01  0:00:01 --:--:-- 8054k
Running PSL Inference
0    [main] INFO  org.linqs.psl.cli.Launcher  - Loading data
3639 [main] INFO  org.linqs.psl.cli.Launcher  - Data loading complete
3640 [main] INFO  org.linqs.psl.cli.Launcher  - Loading model
3714 [main] INFO  org.linqs.psl.cli.Launcher  - Model loading complete
3714 [main] INFO  org.linqs.psl.cli.Launcher  - Starting inference with class: org.linqs.psl.application.inference.MPEInference
9859 [main] INFO  org.linqs.psl.application.inference.MPEInference  - Grounding out model.
14270 [main] INFO  org.linqs.psl.application.inference.MPEInference  - Beginning inference.
27386 [main] INFO  org.linqs.psl.reasoner.admm.ADMMReasoner  - Optimization completed in 500 iterations. Primal res.: 0.9105436, Dual res.: 0.053083748
27399 [main] INFO  org.linqs.psl.application.inference.MPEInference  - Inference complete. Writing results to Database.
33669 [main] INFO  org.linqs.psl.application.inference.MPEInference  - Results committed to database.
33669 [main] INFO  org.linqs.psl.cli.Launcher  - Inference Complete
```

**Comment by eriq-augustine** [comment]
Also, this example is configured to stop after 500 iterations.
What version are you comparing it to?

**Comment by eriq-augustine** [comment]
Do you have a theoretical reason for multiplying epsilonPrimal by 2?

As far as I can tell, there have been a number of changes to ADMMReasoner, but none that induced a bug.
(I did find a small issue with TRACE logging and breaking early, but nothing that would cause unnecessarily long optimization: [eriq-augustine/psl:fd1a0522](https://github.com/eriq-augustine/psl/commit/fd1a052214b466c48cf30ce95030f4276a579745).)

It could be that the changes caused this particular optimization to take longer even is most are faster.
One particular thing that could cause this is that the optimization variables are now initialized to random instead of some default value.

How is it working on other problems?

**Comment by thiswill** [comment]
I'm using the groovy way to run PSL. (The cli way works fine for me). The source code I use is master&develop branch with tag 2.1.0.  Here is part of my output.

[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ social-network-analysis ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ social-network-analysis ---
[INFO] Changes detected - recompiling the module!
[INFO] Using Groovy-Eclipse compiler to compile both Java and Groovy files
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15.703 s
[INFO] Finished at: 2018-08-03T13:30:58+01:00
[INFO] ------------------------------------------------------------------------
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------< org.linqs.psl.examples:social-network-analysis >-----------
[INFO] Building social-network-analysis 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:build-classpath (default-cli) @ social-network-analysis ---
[INFO] Wrote classpath file '/disk/local/v1dkunta/psl-ex2/psl-examples/social-network-analysis/groovy/classpath.out'.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.100 s
[INFO] Finished at: 2018-08-03T13:31:02+01:00
[INFO] ------------------------------------------------------------------------
Running PSL
0    [main] INFO  org.linqs.psl.examples.socialnetworkanalysis.Run  - Defining model rules
215  [main] INFO  org.linqs.psl.examples.socialnetworkanalysis.Run  - Loading data into database
5061 [main] INFO  org.linqs.psl.examples.socialnetworkanalysis.Run  - Starting inference
14959 [main] INFO  org.linqs.psl.application.inference.MPEInference  - Grounding out model.
21252 [main] INFO  org.linqs.psl.application.inference.MPEInference  - Beginning inference.
351672 [main] INFO  org.linqs.psl.reasoner.admm.ADMMReasoner  - Optimization completed in 25000 iterations. Primal res.: 0.627831, Dual res.: 3.879485E-6
351693 [main] INFO  org.linqs.psl.application.inference.MPEInference  - Inference complete. Writing results to Database.
360017 [main] INFO  org.linqs.psl.application.inference.MPEInference  - Results committed to database.
360069 [main] INFO  org.linqs.psl.examples.socialnetworkanalysis.Run  - Inference complete


And after I multiply epsilonPrimal by 2, the optimization can be done within 471 iterations.
